import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import NavBar from "@/components/header/NavBar";
import { Toaster } from "sonner";
import Provider from "./Provider";
import Footer from "@/components/custom/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className="bg-neutral-50 text-neutral-900  w-full"
        >
        <Provider>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
          <NavBar />
          <main className="min-h-screen  text-neutral-900  w-full  overflow-auto scrollbar-hide ">
            <Toaster richColors={true}  position="top-center"/>
            {children}</main>
          <Footer/>
        {/* </ThemeProvider> */}
        </Provider>
        </body>
    </html>
  );
}
